language: php

php:
  - 5.3.3
  - 5.4
  - 5.6
  - 7

before_script:  composer install --dev --prefer-source config -g -- disable-tls true
script: php vendor/bin/phpunit --testsuite "Simpleform" -c phpunit.xml